name: Build & Deploy Vulnado App

on: push
jobs:
  build-deploy:
    name: Build and Deploy Vulnado App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn clean test

      - name: Build the application
        run: |
          mvn clean
          mvn package
